#!/bin/sh

UDC_DIR=/sys/class/udc

function contains() {
	for i in "${files[@]}"
	do
		if [ "$i" == "$1" ]; then
			return 1;
		fi
	done
	return 0
}

function launch_uuc() {
	echo $1 $2
	mkdir /sys/kernel/config/usb_gadget/$1
	cd /sys/kernel/config/usb_gadget/$1

	echo 0x066F > idVendor
	echo 0x37FF > idProduct

	mkdir strings/0x409
	echo 0000000000000000 > strings/0x409/serialnumber
	echo "FSL i.MX Board" > strings/0x409/product
	
	mkdir configs/c.1
	echo 5 > configs/c.1/MaxPower

	mkdir functions/mass_storage.1
	echo 0 > functions/mass_storage.1/stall
	# echo "" > functions/mass_storage.1/iSerialNumber
	echo /fat > functions/mass_storage.1/lun.0/file
	echo 1 > functions/mass_storage.1/lun.0/removable
	ln -s functions/mass_storage.1 configs/c.1/

	echo $1 > UDC

	if [ $2 == "0" ]; then
		echo uuc /dev/utp
		uuc /dev/utp
	else
		echo uuc /dev/utp$2
		uuc /dev/utp$2
	fi

	return 0;
}

last=0;

while true; do
if test "$(ls -A "$UDC_DIR")"; then
	cd $UDC_DIR
	for entry in *
	do
		if contains $entry; then
			files[$last]=$entry;
			id=$last;
			last=`expr $last + 1`;
			echo "Found New UDC: $entry";
			launch_uuc $entry $id &
		fi
	done
	sleep 1
else
	echo "No udc Available!"
	sleep 30
fi
done

echo bye
